name: flutter_opentok_example
description: Demonstrates how to use the flutter_opentok plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_opentok:
    path: ../

flutter:
  uses-material-design: true