name: flutter_opentok
description: OpenTok Flutter - a library for OpenTok iOS and Android SDKs.
version: 0.0.7
author: Indoor Solutions <genert.org@indoor.solutions>
homepage: https://github.com/ninjasolutions/flutter_opentok

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  json_serializable: ^4.1.3

flutter:
  plugin:
    androidPackage: com.flutter_opentok
    pluginClass: FlutterOpentokPlugin
